=== madeindjs/invoice-generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "me": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "website": {
          "type": "string"
        }
      },
      "required": ["name", "address", "phone", "email", "website"]
    },
    "recipient": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      },
      "required": ["name", "address"]
    },
    "fromDate": {
      "type": "string"
    },
    "toDate": {
      "type": "string"
    },
    "issueDate": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "hours": {
            "type": "number"
          }
        },
        "required": ["name", "hours"]
      }
    },
    "pricePerHour": {
      "type": "integer"
    },
    "bankInformations": {
      "type": "string"
    }
  },
  "required": ["id", "me", "recipient", "fromDate", "toDate", "issueDate", "items", "pricePerHour", "bankInformations"]
}

=== madeindjs/invoice-generator/example.json
{
  "id": "INVOICE-0001",
  "me": {
    "name": "Jean L'astuce",
    "address": "1 rue des Lilas, 69001, Lyon",
    "phone": "+336123456",
    "email": "me@example.com",
    "website": "https://example.com"
  },
  "recipient": {
    "name": "ACME",
    "address": "1 avenue des Champs Elys√©e, 75001, Paris"
  },
  "fromDate": "2024-06-10",
  "toDate": "2024-07-07",
  "issueDate": "2024-07-11T08:18:45.748Z",
  "items": [
    {
      "name": "Software development - 2024 W25",
      "hours": 9.5
    },
    {
      "name": "Software development - 2024 W26",
      "hours": 8
    },
    {
      "name": "Software development - 2024 W27",
      "hours": 7.6
    }
  ],
  "pricePerHour": 50,
  "bankInformations": "BIC: ABC1234 | IBAN: FR12 1234 1234 1234 1234 1234 123"
}
